# Project: ÏîÄ¿1
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main.o sample.o feature.o feature_alignment.o alignment.o
LINKOBJ  = main.o sample.o feature.o feature_alignment.o alignment.o
LIBS     = -L"E:/Dev-Cpp/MinGW64/lib" -L"E:/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -L"E:/Python/Lib" -static-libgcc
INCS     = -I"E:/Dev-Cpp/MinGW64/include" -I"E:/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"E:/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"E:/Dev-Cpp/MinGW64/include" -I"E:/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"E:/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"E:/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++" -I"E:/Python/include"
BIN      = project.exe
CXXFLAGS = $(CXXINCS) -std=gnu++11
CFLAGS   = $(INCS) -std=gnu++11
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

sample.o: sample.cpp
	$(CPP) -c sample.cpp -o sample.o $(CXXFLAGS)

feature.o: feature.cpp
	$(CPP) -c feature.cpp -o feature.o $(CXXFLAGS)

feature_alignment.o: feature_alignment.cpp
	$(CPP) -c feature_alignment.cpp -o feature_alignment.o $(CXXFLAGS)

alignment.o: alignment.cpp
	$(CPP) -c alignment.cpp -o alignment.o $(CXXFLAGS)
